In [30]:
import numpy as np
import pandas as pd
import matplotlib.pylab as plt
import matplotlib
import warnings
import xgboost
from xgboost import XGBClassifier

warnings.filterwarnings('ignore')
cust_df = pd.read_csv("./datasets/Santander Customer Satisfaction - TRAIN.csv/Santander Customer Satisfaction - TRAIN.csv", encoding='latin-1')
print('dataset shape:',cust_df.shape)
cust_df.head(3)

dataset shape: (76020, 371)

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.17,0
1,3,2,34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.03,0
2,4,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.77,0

In [31]:
cust_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76020 entries, 0 to 76019
Columns: 371 entries, ID to TARGET
dtypes: float64(111), int64(260)
memory usage: 215.2 MB

In [32]:
print(cust_df['TARGET'].value_counts())
unsatisfied_cnt = cust_df[cust_df['TARGET'] == 1].TARGET.count()
total_cnt=cust_df.TARGET.count()
print('unsatisfied 비율은 {0:.2f}'.format((unsatisfied_cnt/total_cnt)))

TARGET
0    73012
1     3008
Name: count, dtype: int64
unsatisfied 비율은 0.04

In [33]:
cust_df.describe()

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
count,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,...,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,7.602000e+04,76020.000000
mean,75964.050723,-1523.199277,33.212865,86.208265,72.363067,119.529632,3.559130,6.472698,0.412946,0.567352,...,7.935824,1.365146,12.215580,8.784074,31.505324,1.858575,76.026165,56.614351,1.172358e+05,0.039569
std,43781.947379,39033.462364,12.956486,1614.757313,339.315831,546.266294,93.155749,153.737066,30.604864,36.513513,...,455.887218,113.959637,783.207399,538.439211,2013.125393,147.786584,4040.337842,2852.579397,1.826646e+05,0.194945
min,1.000000,-999999.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.163750e+03,0.000000
25%,38104.750000,2.000000,23.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.787061e+04,0.000000
50%,76043.000000,2.000000,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.064092e+05,0.000000
75%,113748.750000,2.000000,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.187563e+05,0.000000
max,151838.000000,238.000000,105.000000,210000.000000,12888.030000,21024.810000,8237.820000,11073.570000,6600.000000,6600.000000,...,50003.880000,20385.720000,138831.630000,91778.730000,438329.220000,24650.010000,681462.900000,397884.300000,2.203474e+07,1.000000

In [34]:
cust_df['var3'].replace(-999999,2,inplace=True)
cust_df.drop('ID', axis=1, inplace=True)

x_features = cust_df.iloc[:,:-1]
y_labels = cust_df.iloc[:,-1]
print('피처 데이터 shape:{0}'.format(x_features.shape))

피처 데이터 shape:(76020, 369)

In [35]:
x_features.describe()

,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,imp_op_var40_ult1,...,saldo_medio_var29_ult3,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38
count,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,...,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,7.602000e+04
mean,2.716483,33.212865,86.208265,72.363067,119.529632,3.559130,6.472698,0.412946,0.567352,3.160715,...,0.186630,7.935824,1.365146,12.215580,8.784074,31.505324,1.858575,76.026165,56.614351,1.172358e+05
std,9.447971,12.956486,1614.757313,339.315831,546.266294,93.155749,153.737066,30.604864,36.513513,95.268204,...,31.879418,455.887218,113.959637,783.207399,538.439211,2013.125393,147.786584,4040.337842,2852.579397,1.826646e+05
min,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.163750e+03
25%,2.000000,23.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.787061e+04
50%,2.000000,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.064092e+05
75%,2.000000,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.187563e+05
max,238.000000,105.000000,210000.000000,12888.030000,21024.810000,8237.820000,11073.570000,6600.000000,6600.000000,8237.820000,...,7331.340000,50003.880000,20385.720000,138831.630000,91778.730000,438329.220000,24650.010000,681462.900000,397884.300000,2.203474e+07

In [36]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_features, y_labels, test_size=0.2, random_state=0)
train_cnt=y_train.count()
test_cnt=y_test.count()
print('학습 세트 shape:{0}, 테스트 세트 shape:{1}'.format(x_train.shape, x_test.shape))

print('학습 세트 레이블 값 분포 비율')
print(y_train.value_counts()/train_cnt)
print('\n 테스트 세트 레이블 값 분포 비율')
print(y_test.value_counts()/test_cnt)

학습 세트 shape:(60816, 369), 테스트 세트 shape:(15204, 369)
학습 세트 레이블 값 분포 비율
TARGET
0    0.960964
1    0.039036
Name: count, dtype: float64

 테스트 세트 레이블 값 분포 비율
TARGET
0    0.9583
1    0.0417
Name: count, dtype: float64

In [37]:
x_tr, x_val, y_tr, y_val = train_test_split(x_train, y_train, test_size=0.3, random_state=0)

In [38]:
#!pip install xgboost
from xgboost import XGBClassifier
from xgboost.callback import EarlyStopping
from sklearn.metrics import roc_auc_score
import inspect
import xgboost
print("xgboost version:", xgboost.__version__)
print("xgboost path:", xgboost.__file__)
print("XGBClassifier module:", XGBClassifier.__module__)
print("fit signature:", inspect.signature(XGBClassifier.fit))

xgboost version: 3.1.2
xgboost path: C:\Users\claire_lee\AppData\Roaming\Python\Python312\site-packages\xgboost\__init__.py
XGBClassifier module: xgboost.sklearn
fit signature: (self, X: Any, y: Any, *, sample_weight: Optional[Any] = None, base_margin: Optional[Any] = None, eval_set: Optional[Sequence[Tuple[Any, Any]]] = None, verbose: Union[bool, int, NoneType] = True, xgb_model: Union[xgboost.core.Booster, str, xgboost.sklearn.XGBModel, NoneType] = None, sample_weight_eval_set: Optional[Sequence[Any]] = None, base_margin_eval_set: Optional[Sequence[Any]] = None, feature_weights: Optional[Any] = None) -> 'XGBClassifier'

In [39]:
xgb_clf = XGBClassifier(n_estimators=500, learning_rate=0.05, random_state=156)
xgb_clf.fit(
    x_tr, y_tr,
    eval_set=[(x_val, y_val)],
    verbose=True
)
xgb_roc_score = roc_auc_score(y_test, xgb_clf.predict_proba(x_test)[:,1])
print('ROC AUC: {0:4f}'.format(xgb_roc_score))

[0]	validation_0-logloss:0.16168
[1]	validation_0-logloss:0.15864
[2]	validation_0-logloss:0.15609
[3]	validation_0-logloss:0.15399
[4]	validation_0-logloss:0.15215
[5]	validation_0-logloss:0.15057
[6]	validation_0-logloss:0.14912
[7]	validation_0-logloss:0.14789
[8]	validation_0-logloss:0.14679
[9]	validation_0-logloss:0.14579
[10]	validation_0-logloss:0.14488
[11]	validation_0-logloss:0.14407
[12]	validation_0-logloss:0.14329
[13]	validation_0-logloss:0.14257
[14]	validation_0-logloss:0.14192
[15]	validation_0-logloss:0.14132
[16]	validation_0-logloss:0.14077
[17]	validation_0-logloss:0.14028
[18]	validation_0-logloss:0.13985
[19]	validation_0-logloss:0.13940
[20]	validation_0-logloss:0.13903
[21]	validation_0-logloss:0.13867
[22]	validation_0-logloss:0.13836
[23]	validation_0-logloss:0.13806
[24]	validation_0-logloss:0.13781
[25]	validation_0-logloss:0.13759
[26]	validation_0-logloss:0.13741
[27]	validation_0-logloss:0.13722
[28]	validation_0-logloss:0.13702
[29]	validation_0-logloss:0.13688
[30]	validation_0-logloss:0.13670
[31]	validation_0-logloss:0.13652
[32]	validation_0-logloss:0.13639
[33]	validation_0-logloss:0.13625
[34]	validation_0-logloss:0.13614
[35]	validation_0-logloss:0.13603
[36]	validation_0-logloss:0.13589
[37]	validation_0-logloss:0.13583
[38]	validation_0-logloss:0.13575
[39]	validation_0-logloss:0.13565
[40]	validation_0-logloss:0.13558
[41]	validation_0-logloss:0.13550
[42]	validation_0-logloss:0.13540
[43]	validation_0-logloss:0.13534
[44]	validation_0-logloss:0.13531
[45]	validation_0-logloss:0.13524
[46]	validation_0-logloss:0.13522
[47]	validation_0-logloss:0.13518
[48]	validation_0-logloss:0.13513
[49]	validation_0-logloss:0.13513
[50]	validation_0-logloss:0.13510
[51]	validation_0-logloss:0.13509
[52]	validation_0-logloss:0.13505
[53]	validation_0-logloss:0.13501
[54]	validation_0-logloss:0.13501
[55]	validation_0-logloss:0.13498
[56]	validation_0-logloss:0.13497
[57]	validation_0-logloss:0.13497
[58]	validation_0-logloss:0.13496
[59]	validation_0-logloss:0.13497
[60]	validation_0-logloss:0.13495
[61]	validation_0-logloss:0.13495
[62]	validation_0-logloss:0.13496
[63]	validation_0-logloss:0.13496
[64]	validation_0-logloss:0.13496
[65]	validation_0-logloss:0.13492
[66]	validation_0-logloss:0.13491
[67]	validation_0-logloss:0.13489
[68]	validation_0-logloss:0.13489
[69]	validation_0-logloss:0.13486
[70]	validation_0-logloss:0.13484
[71]	validation_0-logloss:0.13485
[72]	validation_0-logloss:0.13485
[73]	validation_0-logloss:0.13485
[74]	validation_0-logloss:0.13484
[75]	validation_0-logloss:0.13484
[76]	validation_0-logloss:0.13484
[77]	validation_0-logloss:0.13485
[78]	validation_0-logloss:0.13483
[79]	validation_0-logloss:0.13481
[80]	validation_0-logloss:0.13481
[81]	validation_0-logloss:0.13481
[82]	validation_0-logloss:0.13479
[83]	validation_0-logloss:0.13479
[84]	validation_0-logloss:0.13478
[85]	validation_0-logloss:0.13477
[86]	validation_0-logloss:0.13476
[87]	validation_0-logloss:0.13476
[88]	validation_0-logloss:0.13476
[89]	validation_0-logloss:0.13475
[90]	validation_0-logloss:0.13474
[91]	validation_0-logloss:0.13473
[92]	validation_0-logloss:0.13473
[93]	validation_0-logloss:0.13472
[94]	validation_0-logloss:0.13471
[95]	validation_0-logloss:0.13470
[96]	validation_0-logloss:0.13469
[97]	validation_0-logloss:0.13470
[98]	validation_0-logloss:0.13469
[99]	validation_0-logloss:0.13468
[100]	validation_0-logloss:0.13470
[101]	validation_0-logloss:0.13468
[102]	validation_0-logloss:0.13467
[103]	validation_0-logloss:0.13466
[104]	validation_0-logloss:0.13465
[105]	validation_0-logloss:0.13466
[106]	validation_0-logloss:0.13467
[107]	validation_0-logloss:0.13467
[108]	validation_0-logloss:0.13466
[109]	validation_0-logloss:0.13466
[110]	validation_0-logloss:0.13466
[111]	validation_0-logloss:0.13466
[112]	validation_0-logloss:0.13466
[113]	validation_0-logloss:0.13466
[114]	validation_0-logloss:0.13467
[115]	validation_0-logloss:0.13467
[116]	validation_0-logloss:0.13468
[117]	validation_0-logloss:0.13469
[118]	validation_0-logloss:0.13471
[119]	validation_0-logloss:0.13470
[120]	validation_0-logloss:0.13471
[121]	validation_0-logloss:0.13471
[122]	validation_0-logloss:0.13471
[123]	validation_0-logloss:0.13471
[124]	validation_0-logloss:0.13471
[125]	validation_0-logloss:0.13475
[126]	validation_0-logloss:0.13475
[127]	validation_0-logloss:0.13476
[128]	validation_0-logloss:0.13477
[129]	validation_0-logloss:0.13477
[130]	validation_0-logloss:0.13476
[131]	validation_0-logloss:0.13479
[132]	validation_0-logloss:0.13477
[133]	validation_0-logloss:0.13477
[134]	validation_0-logloss:0.13477
[135]	validation_0-logloss:0.13477
[136]	validation_0-logloss:0.13476
[137]	validation_0-logloss:0.13477
[138]	validation_0-logloss:0.13474
[139]	validation_0-logloss:0.13475
[140]	validation_0-logloss:0.13479
[141]	validation_0-logloss:0.13479
[142]	validation_0-logloss:0.13479
[143]	validation_0-logloss:0.13479
[144]	validation_0-logloss:0.13479
[145]	validation_0-logloss:0.13479
[146]	validation_0-logloss:0.13481
[147]	validation_0-logloss:0.13481
[148]	validation_0-logloss:0.13481
[149]	validation_0-logloss:0.13482
[150]	validation_0-logloss:0.13483
[151]	validation_0-logloss:0.13483
[152]	validation_0-logloss:0.13483
[153]	validation_0-logloss:0.13483
[154]	validation_0-logloss:0.13482
[155]	validation_0-logloss:0.13482
[156]	validation_0-logloss:0.13483
[157]	validation_0-logloss:0.13485
[158]	validation_0-logloss:0.13487
[159]	validation_0-logloss:0.13487
[160]	validation_0-logloss:0.13488
[161]	validation_0-logloss:0.13488
[162]	validation_0-logloss:0.13489
[163]	validation_0-logloss:0.13488
[164]	validation_0-logloss:0.13489
[165]	validation_0-logloss:0.13489
[166]	validation_0-logloss:0.13490
[167]	validation_0-logloss:0.13489
[168]	validation_0-logloss:0.13491
[169]	validation_0-logloss:0.13490
[170]	validation_0-logloss:0.13490
[171]	validation_0-logloss:0.13490
[172]	validation_0-logloss:0.13492
[173]	validation_0-logloss:0.13490
[174]	validation_0-logloss:0.13490
[175]	validation_0-logloss:0.13490
[176]	validation_0-logloss:0.13492
[177]	validation_0-logloss:0.13493
[178]	validation_0-logloss:0.13494
[179]	validation_0-logloss:0.13494
[180]	validation_0-logloss:0.13495
[181]	validation_0-logloss:0.13494
[182]	validation_0-logloss:0.13497
[183]	validation_0-logloss:0.13497
[184]	validation_0-logloss:0.13496
[185]	validation_0-logloss:0.13496
[186]	validation_0-logloss:0.13497
[187]	validation_0-logloss:0.13496
[188]	validation_0-logloss:0.13496
[189]	validation_0-logloss:0.13497
[190]	validation_0-logloss:0.13498
[191]	validation_0-logloss:0.13498
[192]	validation_0-logloss:0.13498
[193]	validation_0-logloss:0.13498
[194]	validation_0-logloss:0.13498
[195]	validation_0-logloss:0.13499
[196]	validation_0-logloss:0.13498
[197]	validation_0-logloss:0.13502
[198]	validation_0-logloss:0.13501
[199]	validation_0-logloss:0.13504
[200]	validation_0-logloss:0.13503
[201]	validation_0-logloss:0.13507
[202]	validation_0-logloss:0.13508
[203]	validation_0-logloss:0.13509
[204]	validation_0-logloss:0.13511
[205]	validation_0-logloss:0.13511
[206]	validation_0-logloss:0.13510
[207]	validation_0-logloss:0.13511
[208]	validation_0-logloss:0.13511
[209]	validation_0-logloss:0.13513
[210]	validation_0-logloss:0.13513
[211]	validation_0-logloss:0.13513
[212]	validation_0-logloss:0.13511
[213]	validation_0-logloss:0.13511
[214]	validation_0-logloss:0.13513
[215]	validation_0-logloss:0.13513
[216]	validation_0-logloss:0.13513
[217]	validation_0-logloss:0.13514
[218]	validation_0-logloss:0.13515
[219]	validation_0-logloss:0.13515
[220]	validation_0-logloss:0.13519
[221]	validation_0-logloss:0.13520
[222]	validation_0-logloss:0.13520
[223]	validation_0-logloss:0.13521
[224]	validation_0-logloss:0.13521
[225]	validation_0-logloss:0.13522
[226]	validation_0-logloss:0.13523
[227]	validation_0-logloss:0.13523
[228]	validation_0-logloss:0.13525
[229]	validation_0-logloss:0.13525
[230]	validation_0-logloss:0.13525
[231]	validation_0-logloss:0.13525
[232]	validation_0-logloss:0.13528
[233]	validation_0-logloss:0.13528
[234]	validation_0-logloss:0.13528
[235]	validation_0-logloss:0.13528
[236]	validation_0-logloss:0.13529
[237]	validation_0-logloss:0.13529
[238]	validation_0-logloss:0.13530
[239]	validation_0-logloss:0.13532
[240]	validation_0-logloss:0.13532
[241]	validation_0-logloss:0.13531
[242]	validation_0-logloss:0.13531
[243]	validation_0-logloss:0.13532
[244]	validation_0-logloss:0.13533
[245]	validation_0-logloss:0.13535
[246]	validation_0-logloss:0.13536
[247]	validation_0-logloss:0.13533
[248]	validation_0-logloss:0.13532
[249]	validation_0-logloss:0.13532
[250]	validation_0-logloss:0.13532
[251]	validation_0-logloss:0.13534
[252]	validation_0-logloss:0.13537
[253]	validation_0-logloss:0.13537
[254]	validation_0-logloss:0.13539
[255]	validation_0-logloss:0.13539
[256]	validation_0-logloss:0.13539
[257]	validation_0-logloss:0.13539
[258]	validation_0-logloss:0.13542
[259]	validation_0-logloss:0.13542
[260]	validation_0-logloss:0.13543
[261]	validation_0-logloss:0.13544
[262]	validation_0-logloss:0.13544
[263]	validation_0-logloss:0.13544
[264]	validation_0-logloss:0.13548
[265]	validation_0-logloss:0.13548
[266]	validation_0-logloss:0.13548
[267]	validation_0-logloss:0.13548
[268]	validation_0-logloss:0.13547
[269]	validation_0-logloss:0.13547
[270]	validation_0-logloss:0.13549
[271]	validation_0-logloss:0.13549
[272]	validation_0-logloss:0.13549
[273]	validation_0-logloss:0.13550
[274]	validation_0-logloss:0.13554
[275]	validation_0-logloss:0.13554
[276]	validation_0-logloss:0.13557
[277]	validation_0-logloss:0.13557
[278]	validation_0-logloss:0.13552
[279]	validation_0-logloss:0.13552
[280]	validation_0-logloss:0.13555
[281]	validation_0-logloss:0.13555
[282]	validation_0-logloss:0.13557
[283]	validation_0-logloss:0.13558
[284]	validation_0-logloss:0.13559
[285]	validation_0-logloss:0.13559
[286]	validation_0-logloss:0.13558
[287]	validation_0-logloss:0.13557
[288]	validation_0-logloss:0.13558
[289]	validation_0-logloss:0.13558
[290]	validation_0-logloss:0.13558
[291]	validation_0-logloss:0.13559
[292]	validation_0-logloss:0.13561
[293]	validation_0-logloss:0.13557
[294]	validation_0-logloss:0.13558
[295]	validation_0-logloss:0.13558
[296]	validation_0-logloss:0.13558
[297]	validation_0-logloss:0.13559
[298]	validation_0-logloss:0.13560
[299]	validation_0-logloss:0.13562
[300]	validation_0-logloss:0.13563
[301]	validation_0-logloss:0.13565
[302]	validation_0-logloss:0.13566
[303]	validation_0-logloss:0.13567
[304]	validation_0-logloss:0.13569
[305]	validation_0-logloss:0.13573
[306]	validation_0-logloss:0.13574
[307]	validation_0-logloss:0.13574
[308]	validation_0-logloss:0.13575
[309]	validation_0-logloss:0.13576
[310]	validation_0-logloss:0.13578
[311]	validation_0-logloss:0.13580
[312]	validation_0-logloss:0.13582
[313]	validation_0-logloss:0.13582
[314]	validation_0-logloss:0.13585
[315]	validation_0-logloss:0.13585
[316]	validation_0-logloss:0.13586
[317]	validation_0-logloss:0.13587
[318]	validation_0-logloss:0.13588
[319]	validation_0-logloss:0.13591
[320]	validation_0-logloss:0.13590
[321]	validation_0-logloss:0.13590
[322]	validation_0-logloss:0.13591
[323]	validation_0-logloss:0.13591
[324]	validation_0-logloss:0.13591
[325]	validation_0-logloss:0.13591
[326]	validation_0-logloss:0.13591
[327]	validation_0-logloss:0.13592
[328]	validation_0-logloss:0.13595
[329]	validation_0-logloss:0.13595
[330]	validation_0-logloss:0.13595
[331]	validation_0-logloss:0.13595
[332]	validation_0-logloss:0.13595
[333]	validation_0-logloss:0.13596
[334]	validation_0-logloss:0.13599
[335]	validation_0-logloss:0.13598
[336]	validation_0-logloss:0.13597
[337]	validation_0-logloss:0.13599
[338]	validation_0-logloss:0.13600
[339]	validation_0-logloss:0.13600
[340]	validation_0-logloss:0.13601
[341]	validation_0-logloss:0.13603
[342]	validation_0-logloss:0.13604
[343]	validation_0-logloss:0.13606
[344]	validation_0-logloss:0.13605
[345]	validation_0-logloss:0.13605
[346]	validation_0-logloss:0.13602
[347]	validation_0-logloss:0.13601
[348]	validation_0-logloss:0.13601
[349]	validation_0-logloss:0.13600
[350]	validation_0-logloss:0.13602
[351]	validation_0-logloss:0.13602
[352]	validation_0-logloss:0.13604
[353]	validation_0-logloss:0.13604
[354]	validation_0-logloss:0.13606
[355]	validation_0-logloss:0.13608
[356]	validation_0-logloss:0.13608
[357]	validation_0-logloss:0.13608
[358]	validation_0-logloss:0.13608
[359]	validation_0-logloss:0.13610
[360]	validation_0-logloss:0.13610
[361]	validation_0-logloss:0.13612
[362]	validation_0-logloss:0.13613
[363]	validation_0-logloss:0.13613
[364]	validation_0-logloss:0.13611
[365]	validation_0-logloss:0.13611
[366]	validation_0-logloss:0.13613
[367]	validation_0-logloss:0.13615
[368]	validation_0-logloss:0.13616
[369]	validation_0-logloss:0.13616
[370]	validation_0-logloss:0.13617
[371]	validation_0-logloss:0.13617
[372]	validation_0-logloss:0.13618
[373]	validation_0-logloss:0.13619
[374]	validation_0-logloss:0.13620
[375]	validation_0-logloss:0.13622
[376]	validation_0-logloss:0.13623
[377]	validation_0-logloss:0.13627
[378]	validation_0-logloss:0.13629
[379]	validation_0-logloss:0.13630
[380]	validation_0-logloss:0.13629
[381]	validation_0-logloss:0.13630
[382]	validation_0-logloss:0.13633
[383]	validation_0-logloss:0.13635
[384]	validation_0-logloss:0.13636
[385]	validation_0-logloss:0.13636
[386]	validation_0-logloss:0.13638
[387]	validation_0-logloss:0.13638
[388]	validation_0-logloss:0.13638
[389]	validation_0-logloss:0.13639
[390]	validation_0-logloss:0.13641
[391]	validation_0-logloss:0.13642
[392]	validation_0-logloss:0.13640
[393]	validation_0-logloss:0.13643
[394]	validation_0-logloss:0.13643
[395]	validation_0-logloss:0.13645
[396]	validation_0-logloss:0.13645
[397]	validation_0-logloss:0.13648
[398]	validation_0-logloss:0.13649
[399]	validation_0-logloss:0.13652
[400]	validation_0-logloss:0.13652
[401]	validation_0-logloss:0.13653
[402]	validation_0-logloss:0.13653
[403]	validation_0-logloss:0.13655
[404]	validation_0-logloss:0.13655
[405]	validation_0-logloss:0.13654
[406]	validation_0-logloss:0.13656
[407]	validation_0-logloss:0.13657
[408]	validation_0-logloss:0.13658
[409]	validation_0-logloss:0.13660
[410]	validation_0-logloss:0.13661
[411]	validation_0-logloss:0.13661
[412]	validation_0-logloss:0.13662
[413]	validation_0-logloss:0.13663
[414]	validation_0-logloss:0.13662
[415]	validation_0-logloss:0.13662
[416]	validation_0-logloss:0.13663
[417]	validation_0-logloss:0.13664
[418]	validation_0-logloss:0.13666
[419]	validation_0-logloss:0.13667
[420]	validation_0-logloss:0.13668
[421]	validation_0-logloss:0.13671
[422]	validation_0-logloss:0.13671
[423]	validation_0-logloss:0.13674
[424]	validation_0-logloss:0.13675
[425]	validation_0-logloss:0.13676
[426]	validation_0-logloss:0.13676
[427]	validation_0-logloss:0.13678
[428]	validation_0-logloss:0.13678
[429]	validation_0-logloss:0.13678
[430]	validation_0-logloss:0.13680
[431]	validation_0-logloss:0.13681
[432]	validation_0-logloss:0.13683
[433]	validation_0-logloss:0.13681
[434]	validation_0-logloss:0.13682
[435]	validation_0-logloss:0.13683
[436]	validation_0-logloss:0.13685
[437]	validation_0-logloss:0.13681
[438]	validation_0-logloss:0.13682
[439]	validation_0-logloss:0.13683
[440]	validation_0-logloss:0.13685
[441]	validation_0-logloss:0.13686
[442]	validation_0-logloss:0.13689
[443]	validation_0-logloss:0.13687
[444]	validation_0-logloss:0.13690
[445]	validation_0-logloss:0.13690
[446]	validation_0-logloss:0.13691
[447]	validation_0-logloss:0.13691
[448]	validation_0-logloss:0.13692
[449]	validation_0-logloss:0.13693
[450]	validation_0-logloss:0.13696
[451]	validation_0-logloss:0.13696
[452]	validation_0-logloss:0.13697
[453]	validation_0-logloss:0.13698
[454]	validation_0-logloss:0.13695
[455]	validation_0-logloss:0.13696
[456]	validation_0-logloss:0.13696
[457]	validation_0-logloss:0.13696
[458]	validation_0-logloss:0.13697
[459]	validation_0-logloss:0.13697
[460]	validation_0-logloss:0.13702
[461]	validation_0-logloss:0.13704
[462]	validation_0-logloss:0.13706
[463]	validation_0-logloss:0.13707
[464]	validation_0-logloss:0.13706
[465]	validation_0-logloss:0.13708
[466]	validation_0-logloss:0.13708
[467]	validation_0-logloss:0.13710
[468]	validation_0-logloss:0.13711
[469]	validation_0-logloss:0.13712
[470]	validation_0-logloss:0.13714
[471]	validation_0-logloss:0.13714
[472]	validation_0-logloss:0.13715
[473]	validation_0-logloss:0.13717
[474]	validation_0-logloss:0.13720
[475]	validation_0-logloss:0.13719
[476]	validation_0-logloss:0.13720
[477]	validation_0-logloss:0.13720
[478]	validation_0-logloss:0.13721
[479]	validation_0-logloss:0.13724
[480]	validation_0-logloss:0.13725
[481]	validation_0-logloss:0.13728
[482]	validation_0-logloss:0.13729
[483]	validation_0-logloss:0.13731
[484]	validation_0-logloss:0.13731
[485]	validation_0-logloss:0.13731
[486]	validation_0-logloss:0.13731
[487]	validation_0-logloss:0.13730
[488]	validation_0-logloss:0.13732
[489]	validation_0-logloss:0.13734
[490]	validation_0-logloss:0.13734
[491]	validation_0-logloss:0.13734
[492]	validation_0-logloss:0.13735
[493]	validation_0-logloss:0.13736
[494]	validation_0-logloss:0.13737
[495]	validation_0-logloss:0.13738
[496]	validation_0-logloss:0.13738
[497]	validation_0-logloss:0.13739
[498]	validation_0-logloss:0.13739
[499]	validation_0-logloss:0.13739
ROC AUC: 0.838535

In [40]:
#!pip install hyperopt
from hyperopt import hp

xgb_search_space = {'max_depth':hp.quniform('max_depth', 5,15,1),
                   'min_child_weight':hp.quniform('min_child_weight',1,6,1),
                   'colsample_bytree':hp.uniform('colsample_bytree', 0.5, 0.95),
                   'learning_rate':hp.uniform('learning_rate', 0.01, 0.2)}

In [41]:
#!pip install -U xgboost
import xgboost
from sklearn.model_selection import KFold
from sklearn.metrics import roc_auc_score

def objective_func(search_space):
    xgb_clf = XGBClassifier(n_estimatores=100, max_depth=int(search_space['max_depth']),
                            min_child_weight=int(search_space['min_child_weight']),
                            solsample_bytree=search_space['colsample_bytree'],
                            learning_rate=search_space['learning_rate'])
    roc_auc_list=[]

    kf = KFold(n_splits=3)
    for tr_index, val_index in kf.split(x_train):
        x_tr, y_tr = x_train.iloc[tr_index], y_train.iloc[tr_index]
        x_val, y_val = x_train.iloc[val_index], y_train.iloc[val_index]
    
    xgb_clf.fit(
        x_tr, y_tr,
        eval_set=[(x_val, y_val)],
        verbose=True
    )

    score = roc_auc_score(y_val, xgb_clf.predict_proba(x_val)[:, 1])
    roc_auc_list.append(score)

    return -1*np.mean(roc_auc_list)

In [ ]:
from hyperopt import fmin, tpe, Trials

trials = Trials()

best = fmin(fn=objective_func, 
            space=xgb_search_space,
            algo=tpe.suggest,
            max_evals=50,
            trials=trials, rstate=np.random.default_rng(seed=30))

print('best:', best)

[0]	validation_0-logloss:0.16171
[1]	validation_0-logloss:0.15716
[2]	validation_0-logloss:0.15375
[3]	validation_0-logloss:0.15105
[4]	validation_0-logloss:0.14879
[5]	validation_0-logloss:0.14703
[6]	validation_0-logloss:0.14560
[7]	validation_0-logloss:0.14437
[8]	validation_0-logloss:0.14331
[9]	validation_0-logloss:0.14241
[10]	validation_0-logloss:0.14158
[11]	validation_0-logloss:0.14095
[12]	validation_0-logloss:0.14034
[13]	validation_0-logloss:0.13984
[14]	validation_0-logloss:0.13938
[15]	validation_0-logloss:0.13896
[16]	validation_0-logloss:0.13858
[17]	validation_0-logloss:0.13826
[18]	validation_0-logloss:0.13796
[19]	validation_0-logloss:0.13773
[20]	validation_0-logloss:0.13754
[21]	validation_0-logloss:0.13738
[22]	validation_0-logloss:0.13722
[23]	validation_0-logloss:0.13712
[24]	validation_0-logloss:0.13705
[25]	validation_0-logloss:0.13694
[26]	validation_0-logloss:0.13684
[27]	validation_0-logloss:0.13671
[28]	validation_0-logloss:0.13664
[29]	validation_0-logloss:0.13659
[30]	validation_0-logloss:0.13653
[31]	validation_0-logloss:0.13648
[32]	validation_0-logloss:0.13643
[33]	validation_0-logloss:0.13640
[34]	validation_0-logloss:0.13642
[35]	validation_0-logloss:0.13633
[36]	validation_0-logloss:0.13628
[37]	validation_0-logloss:0.13628
[38]	validation_0-logloss:0.13622
[39]	validation_0-logloss:0.13615
[40]	validation_0-logloss:0.13615
[41]	validation_0-logloss:0.13609
[42]	validation_0-logloss:0.13610
[43]	validation_0-logloss:0.13607
[44]	validation_0-logloss:0.13605
[45]	validation_0-logloss:0.13609
[46]	validation_0-logloss:0.13605
[47]	validation_0-logloss:0.13605
[48]	validation_0-logloss:0.13606
[49]	validation_0-logloss:0.13607
[50]	validation_0-logloss:0.13610
[51]	validation_0-logloss:0.13607
[52]	validation_0-logloss:0.13606
[53]	validation_0-logloss:0.13606
[54]	validation_0-logloss:0.13611
[55]	validation_0-logloss:0.13615
[56]	validation_0-logloss:0.13616
[57]	validation_0-logloss:0.13618
[58]	validation_0-logloss:0.13619
[59]	validation_0-logloss:0.13623
[60]	validation_0-logloss:0.13621
[61]	validation_0-logloss:0.13625
[62]	validation_0-logloss:0.13625
[63]	validation_0-logloss:0.13628
[64]	validation_0-logloss:0.13628
[65]	validation_0-logloss:0.13623
[66]	validation_0-logloss:0.13623
[67]	validation_0-logloss:0.13623
[68]	validation_0-logloss:0.13624
[69]	validation_0-logloss:0.13625
[70]	validation_0-logloss:0.13624
[71]	validation_0-logloss:0.13626
[72]	validation_0-logloss:0.13629
[73]	validation_0-logloss:0.13633
[74]	validation_0-logloss:0.13638
[75]	validation_0-logloss:0.13639
[76]	validation_0-logloss:0.13634
[77]	validation_0-logloss:0.13634
[78]	validation_0-logloss:0.13632
[79]	validation_0-logloss:0.13635
[80]	validation_0-logloss:0.13635
[81]	validation_0-logloss:0.13638
[82]	validation_0-logloss:0.13640
[83]	validation_0-logloss:0.13643
[84]	validation_0-logloss:0.13644
[85]	validation_0-logloss:0.13644
[86]	validation_0-logloss:0.13648
[87]	validation_0-logloss:0.13652
[88]	validation_0-logloss:0.13650
[89]	validation_0-logloss:0.13652
[90]	validation_0-logloss:0.13653
[91]	validation_0-logloss:0.13653
[92]	validation_0-logloss:0.13654
[93]	validation_0-logloss:0.13656
[94]	validation_0-logloss:0.13656
[95]	validation_0-logloss:0.13661
[96]	validation_0-logloss:0.13663
[97]	validation_0-logloss:0.13663
[98]	validation_0-logloss:0.13663
[99]	validation_0-logloss:0.13665
[0]	validation_0-logloss:0.16373
[1]	validation_0-logloss:0.16003
[2]	validation_0-logloss:0.15719
[3]	validation_0-logloss:0.15462
[4]	validation_0-logloss:0.15257
[5]	validation_0-logloss:0.15090
[6]	validation_0-logloss:0.14935
[7]	validation_0-logloss:0.14795
[8]	validation_0-logloss:0.14673
[9]	validation_0-logloss:0.14577
[10]	validation_0-logloss:0.14495
[11]	validation_0-logloss:0.14419
[12]	validation_0-logloss:0.14341
[13]	validation_0-logloss:0.14280
[14]	validation_0-logloss:0.14225
[15]	validation_0-logloss:0.14174
[16]	validation_0-logloss:0.14129
[17]	validation_0-logloss:0.14089
[18]	validation_0-logloss:0.14049
[19]	validation_0-logloss:0.14012
[20]	validation_0-logloss:0.13976
[21]	validation_0-logloss:0.13947
[22]	validation_0-logloss:0.13921
[23]	validation_0-logloss:0.13900
[24]	validation_0-logloss:0.13878
[25]	validation_0-logloss:0.13861
[26]	validation_0-logloss:0.13846
[27]	validation_0-logloss:0.13826
[28]	validation_0-logloss:0.13809
[29]	validation_0-logloss:0.13803
[30]	validation_0-logloss:0.13792
[31]	validation_0-logloss:0.13783
[32]	validation_0-logloss:0.13773
[33]	validation_0-logloss:0.13765
[34]	validation_0-logloss:0.13757
[35]	validation_0-logloss:0.13749
[36]	validation_0-logloss:0.13743
[37]	validation_0-logloss:0.13737
[38]	validation_0-logloss:0.13732
[39]	validation_0-logloss:0.13726
[40]	validation_0-logloss:0.13723
[41]	validation_0-logloss:0.13721
[42]	validation_0-logloss:0.13721
[43]	validation_0-logloss:0.13720
[44]	validation_0-logloss:0.13713
[45]	validation_0-logloss:0.13711
[46]	validation_0-logloss:0.13711
[47]	validation_0-logloss:0.13713
[48]	validation_0-logloss:0.13712
[49]	validation_0-logloss:0.13712
[50]	validation_0-logloss:0.13711
[51]	validation_0-logloss:0.13715
[52]	validation_0-logloss:0.13716
[53]	validation_0-logloss:0.13718
[54]	validation_0-logloss:0.13717
[55]	validation_0-logloss:0.13715
[56]	validation_0-logloss:0.13715
[57]	validation_0-logloss:0.13714
[58]	validation_0-logloss:0.13716
[59]	validation_0-logloss:0.13716
[60]	validation_0-logloss:0.13716
[61]	validation_0-logloss:0.13718
[62]	validation_0-logloss:0.13716
[63]	validation_0-logloss:0.13719
[64]	validation_0-logloss:0.13721
[65]	validation_0-logloss:0.13721
[66]	validation_0-logloss:0.13723
[67]	validation_0-logloss:0.13721
[68]	validation_0-logloss:0.13724
[69]	validation_0-logloss:0.13727
[70]	validation_0-logloss:0.13731
[71]	validation_0-logloss:0.13734
[72]	validation_0-logloss:0.13735
[73]	validation_0-logloss:0.13738
[74]	validation_0-logloss:0.13740
[75]	validation_0-logloss:0.13743
[76]	validation_0-logloss:0.13743
[77]	validation_0-logloss:0.13743
[78]	validation_0-logloss:0.13745
[79]	validation_0-logloss:0.13749
[80]	validation_0-logloss:0.13749
[81]	validation_0-logloss:0.13749
[82]	validation_0-logloss:0.13750
[83]	validation_0-logloss:0.13750
[84]	validation_0-logloss:0.13751
[85]	validation_0-logloss:0.13753
[86]	validation_0-logloss:0.13753
[87]	validation_0-logloss:0.13755
[88]	validation_0-logloss:0.13756
[89]	validation_0-logloss:0.13757
[90]	validation_0-logloss:0.13759
[91]	validation_0-logloss:0.13758
[92]	validation_0-logloss:0.13761
[93]	validation_0-logloss:0.13765
[94]	validation_0-logloss:0.13771
[95]	validation_0-logloss:0.13771
[96]	validation_0-logloss:0.13771
[97]	validation_0-logloss:0.13771
[98]	validation_0-logloss:0.13772
[99]	validation_0-logloss:0.13773
[0]	validation_0-logloss:0.15824
[1]	validation_0-logloss:0.15281
[2]	validation_0-logloss:0.14887
[3]	validation_0-logloss:0.14637
[4]	validation_0-logloss:0.14443
[5]	validation_0-logloss:0.14287
[6]	validation_0-logloss:0.14173
[7]	validation_0-logloss:0.14093
[8]	validation_0-logloss:0.14010
[9]	validation_0-logloss:0.13949
[10]	validation_0-logloss:0.13900
[11]	validation_0-logloss:0.13867
[12]	validation_0-logloss:0.13851
[13]	validation_0-logloss:0.13835
[14]	validation_0-logloss:0.13816
[15]	validation_0-logloss:0.13803
[16]	validation_0-logloss:0.13798
[17]	validation_0-logloss:0.13799
[18]	validation_0-logloss:0.13798
[19]	validation_0-logloss:0.13789
[20]	validation_0-logloss:0.13787
[21]	validation_0-logloss:0.13785
[22]	validation_0-logloss:0.13786
[23]	validation_0-logloss:0.13783
[24]	validation_0-logloss:0.13789
[25]	validation_0-logloss:0.13783
[26]	validation_0-logloss:0.13782
[27]	validation_0-logloss:0.13791
[28]	validation_0-logloss:0.13806
[29]	validation_0-logloss:0.13811
[30]	validation_0-logloss:0.13815
[31]	validation_0-logloss:0.13821
[32]	validation_0-logloss:0.13827
[33]	validation_0-logloss:0.13826
[34]	validation_0-logloss:0.13824
[35]	validation_0-logloss:0.13828
[36]	validation_0-logloss:0.13831
[37]	validation_0-logloss:0.13840
[38]	validation_0-logloss:0.13847
[39]	validation_0-logloss:0.13851
[40]	validation_0-logloss:0.13850
[41]	validation_0-logloss:0.13852
[42]	validation_0-logloss:0.13852
[43]	validation_0-logloss:0.13857
[44]	validation_0-logloss:0.13861
[45]	validation_0-logloss:0.13862
[46]	validation_0-logloss:0.13867
[47]	validation_0-logloss:0.13870
[48]	validation_0-logloss:0.13877
[49]	validation_0-logloss:0.13885
[50]	validation_0-logloss:0.13892
[51]	validation_0-logloss:0.13900
[52]	validation_0-logloss:0.13909
[53]	validation_0-logloss:0.13910
[54]	validation_0-logloss:0.13916
[55]	validation_0-logloss:0.13919
[56]	validation_0-logloss:0.13930
[57]	validation_0-logloss:0.13934
[58]	validation_0-logloss:0.13939
[59]	validation_0-logloss:0.13942
[60]	validation_0-logloss:0.13942
[61]	validation_0-logloss:0.13948
[62]	validation_0-logloss:0.13953
[63]	validation_0-logloss:0.13956
[64]	validation_0-logloss:0.13964
[65]	validation_0-logloss:0.13982
[66]	validation_0-logloss:0.13984
[67]	validation_0-logloss:0.13997
[68]	validation_0-logloss:0.14002
[69]	validation_0-logloss:0.14011
[70]	validation_0-logloss:0.14018
[71]	validation_0-logloss:0.14027
[72]	validation_0-logloss:0.14030
[73]	validation_0-logloss:0.14035
[74]	validation_0-logloss:0.14040
[75]	validation_0-logloss:0.14043
[76]	validation_0-logloss:0.14048
[77]	validation_0-logloss:0.14053
[78]	validation_0-logloss:0.14057
[79]	validation_0-logloss:0.14071
[80]	validation_0-logloss:0.14086
[81]	validation_0-logloss:0.14092
[82]	validation_0-logloss:0.14096
[83]	validation_0-logloss:0.14100
[84]	validation_0-logloss:0.14107
[85]	validation_0-logloss:0.14125
[86]	validation_0-logloss:0.14129
[87]	validation_0-logloss:0.14135
[88]	validation_0-logloss:0.14145
[89]	validation_0-logloss:0.14147
[90]	validation_0-logloss:0.14158
[91]	validation_0-logloss:0.14160
[92]	validation_0-logloss:0.14161
[93]	validation_0-logloss:0.14168
[94]	validation_0-logloss:0.14186
[95]	validation_0-logloss:0.14209
[96]	validation_0-logloss:0.14217
[97]	validation_0-logloss:0.14217
[98]	validation_0-logloss:0.14224
[99]	validation_0-logloss:0.14231
[0]	validation_0-logloss:0.16506
[1]	validation_0-logloss:0.16219
[2]	validation_0-logloss:0.15976
[3]	validation_0-logloss:0.15764
[4]	validation_0-logloss:0.15591
[5]	validation_0-logloss:0.15419
[6]	validation_0-logloss:0.15274
[7]	validation_0-logloss:0.15149
[8]	validation_0-logloss:0.15039
[9]	validation_0-logloss:0.14929
[10]	validation_0-logloss:0.14831
[11]	validation_0-logloss:0.14736
[12]	validation_0-logloss:0.14659
[13]	validation_0-logloss:0.14588
[14]	validation_0-logloss:0.14522
[15]	validation_0-logloss:0.14463
[16]	validation_0-logloss:0.14409
[17]	validation_0-logloss:0.14356
[18]	validation_0-logloss:0.14311
[19]	validation_0-logloss:0.14271
[20]	validation_0-logloss:0.14230
[21]	validation_0-logloss:0.14191
[22]	validation_0-logloss:0.14162
[23]	validation_0-logloss:0.14133
[24]	validation_0-logloss:0.14106
[25]	validation_0-logloss:0.14080
[26]	validation_0-logloss:0.14053
[27]	validation_0-logloss:0.14031
[28]	validation_0-logloss:0.14005
[29]	validation_0-logloss:0.13982
[30]	validation_0-logloss:0.13964
[31]	validation_0-logloss:0.13944
[32]	validation_0-logloss:0.13929
[33]	validation_0-logloss:0.13911
[34]	validation_0-logloss:0.13895
[35]	validation_0-logloss:0.13881
[36]	validation_0-logloss:0.13870
[37]	validation_0-logloss:0.13858
[38]	validation_0-logloss:0.13849
[39]	validation_0-logloss:0.13838
[40]	validation_0-logloss:0.13830
[41]	validation_0-logloss:0.13821
[42]	validation_0-logloss:0.13813
[43]	validation_0-logloss:0.13809
[44]	validation_0-logloss:0.13801
[45]	validation_0-logloss:0.13797
[46]	validation_0-logloss:0.13800
[47]	validation_0-logloss:0.13796
[48]	validation_0-logloss:0.13793
[49]	validation_0-logloss:0.13790
[50]	validation_0-logloss:0.13785
[51]	validation_0-logloss:0.13783
[52]	validation_0-logloss:0.13781
[53]	validation_0-logloss:0.13780
[54]	validation_0-logloss:0.13778
[55]	validation_0-logloss:0.13773
[56]	validation_0-logloss:0.13772
[57]	validation_0-logloss:0.13769
[58]	validation_0-logloss:0.13767
[59]	validation_0-logloss:0.13766
[60]	validation_0-logloss:0.13765
[61]	validation_0-logloss:0.13764
[62]	validation_0-logloss:0.13763
[63]	validation_0-logloss:0.13762
[64]	validation_0-logloss:0.13759
[65]	validation_0-logloss:0.13757
[66]	validation_0-logloss:0.13755
[67]	validation_0-logloss:0.13755
[68]	validation_0-logloss:0.13753
[69]	validation_0-logloss:0.13754
[70]	validation_0-logloss:0.13754
[71]	validation_0-logloss:0.13754
[72]	validation_0-logloss:0.13755
[73]	validation_0-logloss:0.13755
[74]	validation_0-logloss:0.13755
[75]	validation_0-logloss:0.13758
[76]	validation_0-logloss:0.13758
[77]	validation_0-logloss:0.13757
[78]	validation_0-logloss:0.13755
[79]	validation_0-logloss:0.13754
[80]	validation_0-logloss:0.13756
[81]	validation_0-logloss:0.13752
[82]	validation_0-logloss:0.13753
[83]	validation_0-logloss:0.13753
[84]	validation_0-logloss:0.13753
[85]	validation_0-logloss:0.13753
[86]	validation_0-logloss:0.13755
[87]	validation_0-logloss:0.13756
[88]	validation_0-logloss:0.13756
[89]	validation_0-logloss:0.13755
[90]	validation_0-logloss:0.13758
[91]	validation_0-logloss:0.13757
[92]	validation_0-logloss:0.13759
[93]	validation_0-logloss:0.13760
[94]	validation_0-logloss:0.13763
[95]	validation_0-logloss:0.13763
[96]	validation_0-logloss:0.13766
[97]	validation_0-logloss:0.13769
[98]	validation_0-logloss:0.13772
[99]	validation_0-logloss:0.13776
[0]	validation_0-logloss:0.15633
[1]	validation_0-logloss:0.15073
[2]	validation_0-logloss:0.14700
[3]	validation_0-logloss:0.14453
[4]	validation_0-logloss:0.14301
[5]	validation_0-logloss:0.14186
[6]	validation_0-logloss:0.14092
[7]	validation_0-logloss:0.14027
[8]	validation_0-logloss:0.13987
[9]	validation_0-logloss:0.13954
[10]	validation_0-logloss:0.13933
[11]	validation_0-logloss:0.13910
[12]	validation_0-logloss:0.13895
[13]	validation_0-logloss:0.13878
[14]	validation_0-logloss:0.13863
[15]	validation_0-logloss:0.13862
[16]	validation_0-logloss:0.13864
[17]	validation_0-logloss:0.13859
[18]	validation_0-logloss:0.13858
[19]	validation_0-logloss:0.13859
[20]	validation_0-logloss:0.13874
[21]	validation_0-logloss:0.13876
[22]	validation_0-logloss:0.13872
[23]	validation_0-logloss:0.13875
[24]	validation_0-logloss:0.13884
[25]	validation_0-logloss:0.13884
[26]	validation_0-logloss:0.13892
[27]	validation_0-logloss:0.13885
[28]	validation_0-logloss:0.13890
[29]	validation_0-logloss:0.13893
[30]	validation_0-logloss:0.13899
[31]	validation_0-logloss:0.13912
[32]	validation_0-logloss:0.13914
[33]	validation_0-logloss:0.13921
[34]	validation_0-logloss:0.13925
[35]	validation_0-logloss:0.13929
[36]	validation_0-logloss:0.13933
[37]	validation_0-logloss:0.13946
[38]	validation_0-logloss:0.13959
[39]	validation_0-logloss:0.13962
[40]	validation_0-logloss:0.13969
[41]	validation_0-logloss:0.13976
[42]	validation_0-logloss:0.13977
[43]	validation_0-logloss:0.13980
[44]	validation_0-logloss:0.13991
[45]	validation_0-logloss:0.13993
[46]	validation_0-logloss:0.14004
[47]	validation_0-logloss:0.14010
[48]	validation_0-logloss:0.14033
[49]	validation_0-logloss:0.14039
[50]	validation_0-logloss:0.14046
[51]	validation_0-logloss:0.14052
[52]	validation_0-logloss:0.14061
[53]	validation_0-logloss:0.14066
[54]	validation_0-logloss:0.14080
[55]	validation_0-logloss:0.14097
[56]	validation_0-logloss:0.14113
[57]	validation_0-logloss:0.14117
[58]	validation_0-logloss:0.14127
[59]	validation_0-logloss:0.14140
[60]	validation_0-logloss:0.14152
[61]	validation_0-logloss:0.14163
[62]	validation_0-logloss:0.14176
[63]	validation_0-logloss:0.14189
[64]	validation_0-logloss:0.14198
[65]	validation_0-logloss:0.14203
[66]	validation_0-logloss:0.14210
[67]	validation_0-logloss:0.14217
[68]	validation_0-logloss:0.14223
[69]	validation_0-logloss:0.14238
[70]	validation_0-logloss:0.14247
[71]	validation_0-logloss:0.14251
[72]	validation_0-logloss:0.14259
[73]	validation_0-logloss:0.14272
[74]	validation_0-logloss:0.14286
[75]	validation_0-logloss:0.14294
[76]	validation_0-logloss:0.14313
[77]	validation_0-logloss:0.14334
[78]	validation_0-logloss:0.14358
[79]	validation_0-logloss:0.14387
[80]	validation_0-logloss:0.14394
[81]	validation_0-logloss:0.14405
[82]	validation_0-logloss:0.14410
[83]	validation_0-logloss:0.14411
[84]	validation_0-logloss:0.14414
[85]	validation_0-logloss:0.14432
[86]	validation_0-logloss:0.14453
[87]	validation_0-logloss:0.14470
[88]	validation_0-logloss:0.14479
[89]	validation_0-logloss:0.14498
[90]	validation_0-logloss:0.14508
[91]	validation_0-logloss:0.14517
[92]	validation_0-logloss:0.14524
[93]	validation_0-logloss:0.14527
[94]	validation_0-logloss:0.14539
[95]	validation_0-logloss:0.14555
[96]	validation_0-logloss:0.14557
[97]	validation_0-logloss:0.14584
[98]	validation_0-logloss:0.14604
[99]	validation_0-logloss:0.14616
[0]	validation_0-logloss:0.16160
[1]	validation_0-logloss:0.15689
[2]	validation_0-logloss:0.15348
[3]	validation_0-logloss:0.15066
[4]	validation_0-logloss:0.14845
[5]	validation_0-logloss:0.14668
[6]	validation_0-logloss:0.14526
[7]	validation_0-logloss:0.14407
[8]	validation_0-logloss:0.14305
[9]	validation_0-logloss:0.14217
[10]	validation_0-logloss:0.14145
[11]	validation_0-logloss:0.14086
[12]	validation_0-logloss:0.14024
[13]	validation_0-logloss:0.13972
[14]	validation_0-logloss:0.13930
[15]	validation_0-logloss:0.13891
[16]	validation_0-logloss:0.13862
[17]	validation_0-logloss:0.13839
[18]	validation_0-logloss:0.13819
[19]	validation_0-logloss:0.13799
[20]	validation_0-logloss:0.13781
[21]	validation_0-logloss:0.13766
[22]	validation_0-logloss:0.13751
[23]	validation_0-logloss:0.13744
[24]	validation_0-logloss:0.13735
[25]	validation_0-logloss:0.13723
[26]	validation_0-logloss:0.13718
[27]	validation_0-logloss:0.13711
[28]	validation_0-logloss:0.13705
[29]	validation_0-logloss:0.13697
[30]	validation_0-logloss:0.13690
[31]	validation_0-logloss:0.13690
[32]	validation_0-logloss:0.13687
[33]	validation_0-logloss:0.13685
[34]	validation_0-logloss:0.13683
[35]	validation_0-logloss:0.13685
[36]	validation_0-logloss:0.13674
[37]	validation_0-logloss:0.13671
[38]	validation_0-logloss:0.13675
[39]	validation_0-logloss:0.13672
[40]	validation_0-logloss:0.13670
[41]	validation_0-logloss:0.13668
[42]	validation_0-logloss:0.13665
[43]	validation_0-logloss:0.13663
[44]	validation_0-logloss:0.13665
[45]	validation_0-logloss:0.13665
[46]	validation_0-logloss:0.13669
[47]	validation_0-logloss:0.13672
[48]	validation_0-logloss:0.13667
[49]	validation_0-logloss:0.13669
[50]	validation_0-logloss:0.13671
[51]	validation_0-logloss:0.13669
[52]	validation_0-logloss:0.13670
[53]	validation_0-logloss:0.13674
[54]	validation_0-logloss:0.13675
[55]	validation_0-logloss:0.13678
[56]	validation_0-logloss:0.13679
[57]	validation_0-logloss:0.13683
[58]	validation_0-logloss:0.13684
[59]	validation_0-logloss:0.13685
[60]	validation_0-logloss:0.13688
[61]	validation_0-logloss:0.13688
[62]	validation_0-logloss:0.13689
[63]	validation_0-logloss:0.13691
[64]	validation_0-logloss:0.13695
[65]	validation_0-logloss:0.13690
[66]	validation_0-logloss:0.13684
[67]	validation_0-logloss:0.13683
[68]	validation_0-logloss:0.13686
[69]	validation_0-logloss:0.13687
[70]	validation_0-logloss:0.13689
[71]	validation_0-logloss:0.13688
[72]	validation_0-logloss:0.13690
[73]	validation_0-logloss:0.13690
[74]	validation_0-logloss:0.13695
[75]	validation_0-logloss:0.13697
[76]	validation_0-logloss:0.13701
[77]	validation_0-logloss:0.13702
[78]	validation_0-logloss:0.13702
[79]	validation_0-logloss:0.13703
[80]	validation_0-logloss:0.13703
[81]	validation_0-logloss:0.13703
[82]	validation_0-logloss:0.13707
[83]	validation_0-logloss:0.13707
[84]	validation_0-logloss:0.13708
[85]	validation_0-logloss:0.13710
[86]	validation_0-logloss:0.13711
[87]	validation_0-logloss:0.13709
[88]	validation_0-logloss:0.13705
[89]	validation_0-logloss:0.13712

In [ ]:
xgb_clf = XGBClassifier(n_estimators=500, learning_rate=round(best['learning_rate'],5),
                        max_depth=int(best['max_depth']),
                        min_child_weight=int(best['min_child_weight']),
                        colsample_bytree=round(best['colsample_bytree'], 5))
xgb_clf.fit(x_tr, y_tr, early_stopping_rounds=100,
           eval_metric="auc", eval_set = [(x_tr, y_tr),(x_val, y_val)])

xgb_roc_score=roc_auc_score(y_test, xgb_clf.predict_proba(x_test)[:,1])

print('ROC AUC:{0:.4f}'.format(xgb_roc_score))